//! Post-process rustdoc HTML pages and inject rendered safety requirements.
//!
//! # Overview
//!
//! This tool scans Rust source files for `#[safety::requires(...)]`, renders them
//! with spec-driven text templates, and patches matching `fn.*.html` pages generated by rustdoc.
//!
//! Injected content uses the same HTML shape as rustdoc Safety lists , placed immediately **after**
//! rustdoc’s `# Safety` heading (or start of main docblock if missing).
//!
//! For example, if the source file contains:
//! ```rust
//! #[safety::requires(ValidPtrRead(src, T, 1))]
//! fn foo() {
//!     // ...
//! }
//! ```
//!
//! The generated HTML will look like:
//! ```html
//! <!-- safety-tool:start --><ul data-safety-tool="true">
//! <li>
//! <p>ValidPtrRead: pointer <code>src</code> must be <a href="…">valid</a> for reading the <code>sizeof(T) * 1</code> memory from it.</p>
//! </li>
//! </ul>
//! <!-- safety-tool:end -->
//! ```
//!
//! # TOML format
//!
//! The TOML file specifies the crate name, the tags with their descriptions and arguments.
//! ```toml
//! package.name = "core"
//!
//! [tag.ValidPtrRead]
//! args = ["p", "T", "len"]
//! desc = "pointer `{p}` must be [valid](@mod:ptr#safety) for reading the `sizeof({T})* {len}` memory from it."
//! ```
//!
//! Plain relative URLs must pass `is_safe_relative_href`. Logical links `@mod:MODULE#fragment`
//! (module path uses `::`, e.g. `@mod:mem::maybe_uninit#safety`) resolve to the correct
//! `…/index.html#fragment` relative to the **current** `fn.*.html` page.
//!
//! This tool runs only when `package.name` matches the crate being documented.
//!
//! # Markdown links in `desc`
//!
//! Outside of `` `code` `` spans, `desc` may use inline links `[label](url)` (CommonMark-style).
//! They become `<a href="url">label</a>` after `{arg}` substitution. Only **relative** URLs are
//! accepted (same rules as `is_safe_relative_href`); unsafe or absolute URLs are left as plain
//! text starting at the opening `[` so the line still renders.
//!
//! **Logical links** `[label](@mod:path#frag)` resolve at injection time against the documented
//! crate (`package.name`): target file is `{doc_root}/{crate}/{path}/index.html`, with a path
//! relative to the directory of the current function’s HTML file.

use std::collections::HashMap;
use std::path::{Component, Path, PathBuf};
use std::{env, fs};

use quote::ToTokens;
use syn::parse::{Parse, ParseStream};
use syn::punctuated::Punctuated;
use syn::token::{Brace, Paren};
use syn::visit::Visit;
use syn::{Attribute, Expr, Token, Visibility};
use walkdir::WalkDir;

/// Return the value that follows a CLI flag, e.g. `--src-root path`.
fn parse_arg_value(args: &[String], name: &str) -> Option<String> {
    let mut i = 0;
    while i < args.len() {
        if args[i] == name {
            return args.get(i + 1).cloned();
        }
        i += 1;
    }
    None
}

/// Parsed `[tag.*]` entry: positional `args` names and `desc` template with `{name}` holes.
#[derive(Debug, Clone)]
struct TagDef {
    /// Placeholder names used in `desc`, such as `{place}`.
    args: Vec<String>,
    /// Human readable text template loaded from spec.
    desc: String,
}

#[derive(Debug, Clone)]
struct Annotation {
    /// Rust module path used to map to rustdoc output directories.
    module_path: Vec<String>,
    func_name: String,
    /// Rendered bullet lines shown in the injected note.
    rendered_lines: Vec<String>,
}

/// Safety spec: crate name and tags.
#[derive(Debug, Clone)]
struct SafetySpec {
    /// Crate name from TOML `package.name` (must match the documented crate).
    #[allow(dead_code)]
    package_name: String,
    tags: HashMap<String, TagDef>,
}

/// Loads the safety spec from the given path. Returns `None` if the crate name does not match.
fn load_safety_spec(path: &Path, documenting_crate: &str) -> Result<Option<SafetySpec>, String> {
    let content = fs::read_to_string(path)
        .map_err(|e| format!("failed to read safety spec {}: {e}", path.display()))?;
    let value: toml::Value = toml::from_str(&content)
        .map_err(|e| format!("failed to parse TOML {}: {e}", path.display()))?;

    let package_name = value
        .get("package")
        .and_then(|v| v.as_table())
        .and_then(|t| t.get("name"))
        .and_then(|v| v.as_str())
        .unwrap_or("core")
        .to_string();

    if package_name != documenting_crate {
        return Ok(None);
    }

    let Some(tag_table) = value.get("tag").and_then(|v| v.as_table()) else {
        return Err(format!("missing `[tag.*]` tables in {}", path.display()));
    };

    let mut tags = HashMap::new();
    for (tag_name, item) in tag_table {
        let Some(item_table) = item.as_table() else {
            continue;
        };
        let args = item_table
            .get("args")
            .and_then(|v| v.as_array())
            .map(|arr| {
                arr.iter().filter_map(|v| v.as_str().map(ToString::to_string)).collect::<Vec<_>>()
            })
            .unwrap_or_default();
        let Some(desc) = item_table.get("desc").and_then(|v| v.as_str()) else {
            continue;
        };
        tags.insert(tag_name.to_string(), TagDef { args, desc: desc.to_string() });
    }

    if tags.is_empty() {
        return Err(format!("no valid `[tag.*]` entries in {}", path.display()));
    }

    Ok(Some(SafetySpec { package_name, tags }))
}

/// Renders the description template with the given values.
///
/// # Arguments
///
/// * `def` - The tag definition.
/// * `values` - The values to substitute into the template.
///
/// # Returns
///
/// The rendered description.
///
/// # Examples
///
/// ```no_run
/// let def = TagDef { args: vec!["p", "T", "len"], desc: "pointer `{p}` must be valid for reading the `sizeof({T})* {len}` memory from it" };
/// let values = vec!["dst", "i32", "1"];
/// let rendered = render_desc(&def, &values);
/// assert_eq!(rendered, "pointer `dst` must be valid for reading the `sizeof(i32)* 1` memory from it");
/// ```
fn render_desc(def: &TagDef, values: &[String]) -> String {
    let mut rendered = def.desc.clone();
    for (i, arg_name) in def.args.iter().enumerate() {
        if let Some(value) = values.get(i) {
            rendered = rendered.replace(&format!("{{{arg_name}}}"), value);
        }
    }
    rendered
}

/// One safety requirement entry parsed from inside `#[safety::requires(...)]`.
///
/// For example, `ValidPtrRead(src, T, 1)` yields `tag == "ValidPtrRead"` and `args` holds three
/// [`syn::Expr`] values. Their string forms fill `{name}` placeholders in
/// the matching `[tag.ValidPtrRead]` `desc` template from the safety spec TOML.
#[derive(Clone)]
struct Property {
    /// Safety requirement tag identifier; when the spec defines this name, `render_property` uses its `desc`.
    tag: String,
    /// Positional arguments in source order, aligned with the spec’s `args` array for that tag.
    args: Vec<Expr>,
}

impl Parse for Property {
    fn parse(input: ParseStream<'_>) -> syn::Result<Self> {
        let tag: syn::Ident = input.parse()?;
        let tag = tag.to_string();
        // Accept both `(a, b)` and `{a, b}` argument forms.
        let args = if input.peek(Paren) {
            let content;
            syn::parenthesized!(content in input);
            Punctuated::<Expr, Token![,]>::parse_terminated(&content)?.into_iter().collect()
        } else if input.peek(Brace) {
            let content;
            syn::braced!(content in input);
            Punctuated::<Expr, Token![,]>::parse_terminated(&content)?.into_iter().collect()
        } else {
            Vec::new()
        };
        Ok(Property { tag, args })
    }
}

/// The full parenthesized payload of `#[safety::requires(...)]`: a comma-separated list of tags.
///
/// Example: `#[safety::requires(ValidPtrRead(p, T, 1), Init(p, T))]` parses to two [`Property`]
/// values in `tags`, which the collector turns into HTML bullet lines.
#[derive(Clone)]
struct SafetyAttrArgs {
    /// Parsed tags in source order, one [`Property`] per comma-separated item.
    tags: Vec<Property>,
}

impl Parse for SafetyAttrArgs {
    fn parse(input: ParseStream<'_>) -> syn::Result<Self> {
        Ok(SafetyAttrArgs {
            tags: Punctuated::<Property, Token![,]>::parse_terminated(input)?.into_iter().collect(),
        })
    }
}

/// Parse `#[safety::requires(...)]` attributes.
fn parse_safety_attr(attr: &Attribute) -> Option<SafetyAttrArgs> {
    let mut segs = attr.path().segments.iter();
    let first = segs.next()?.ident.to_string();
    let second = segs.next()?.ident.to_string();
    if segs.next().is_some() {
        return None;
    }
    if first != "safety" {
        return None;
    }
    if second != "requires" {
        return None;
    }
    attr.parse_args().ok()
}

/// Checks if the function has `#[doc(hidden)]` attribute.
fn has_doc_hidden(attrs: &[Attribute]) -> bool {
    for attr in attrs {
        if !attr.path().is_ident("doc") {
            continue;
        }

        let mut hidden = false;
        let _ = attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("hidden") {
                hidden = true;
            }
            Ok(())
        });

        if hidden {
            return true;
        }
    }
    false
}

/// Checks if the function is public.
fn is_public_fn(vis: &Visibility) -> bool {
    matches!(vis, Visibility::Public(_))
}

/// Converts a `syn::Expr` to a string.
fn expr_to_string(expr: &Expr) -> String {
    expr.to_token_stream().to_string()
}

fn render_property(prop: &Property, spec_tags: &HashMap<String, TagDef>) -> String {
    let args = prop.args.iter().map(expr_to_string).collect::<Vec<_>>();
    let tag_name = &prop.tag;
    if let Some(def) = spec_tags.get(tag_name) {
        let rendered = render_desc(def, &args);
        return format!("{tag_name}: {rendered}");
    }

    if args.is_empty() {
        return tag_name.clone();
    }

    format!("{}({})", tag_name, args.join(", "))
}

fn module_path_from_file(src_root: &Path, file_path: &Path) -> Option<Vec<String>> {
    let rel = file_path.strip_prefix(src_root).ok()?;
    let mut comps = rel.iter().map(|s| s.to_string_lossy().to_string()).collect::<Vec<_>>();
    if comps.is_empty() {
        return Some(Vec::new());
    }

    let file = comps.pop()?;
    // `lib.rs` and `mod.rs` map to their containing module path.
    if file == "lib.rs" {
        return Some(comps);
    }
    if file == "mod.rs" {
        return Some(comps);
    }

    let stem = file.strip_suffix(".rs")?.to_string();
    comps.push(stem);
    Some(comps)
}

struct FileCollector<'a> {
    /// Module path implied by the file location.
    base_module: Vec<String>,
    /// Extra inline module nesting while visiting `mod { ... }` blocks.
    module_stack: Vec<String>,
    spec_tags: &'a HashMap<String, TagDef>,
    out: Vec<Annotation>,
}

impl<'a> FileCollector<'a> {
    fn full_module_path(&self) -> Vec<String> {
        let mut path = self.base_module.clone();
        path.extend(self.module_stack.iter().cloned());
        path
    }
}

impl<'ast, 'a> Visit<'ast> for FileCollector<'a> {
    fn visit_item_fn(&mut self, i: &'ast syn::ItemFn) {
        // Keep output aligned with rustdoc visibility behavior.
        if !is_public_fn(&i.vis) || has_doc_hidden(&i.attrs) {
            syn::visit::visit_item_fn(self, i);
            return;
        }

        let mut lines = Vec::new();
        for attr in &i.attrs {
            if let Some(parsed) = parse_safety_attr(attr) {
                for prop in &parsed.tags {
                    lines.push(render_property(prop, self.spec_tags));
                }
            }
        }

        if !lines.is_empty() {
            self.out.push(Annotation {
                module_path: self.full_module_path(),
                func_name: i.sig.ident.to_string(),
                rendered_lines: lines,
            });
        }

        syn::visit::visit_item_fn(self, i);
    }

    fn visit_item_mod(&mut self, i: &'ast syn::ItemMod) {
        if i.content.is_some() {
            self.module_stack.push(i.ident.to_string());
            syn::visit::visit_item_mod(self, i);
            self.module_stack.pop();
            return;
        }
        syn::visit::visit_item_mod(self, i);
    }
}

fn collect_annotations(src_root: &Path, spec_tags: &HashMap<String, TagDef>) -> Vec<Annotation> {
    let mut out = Vec::new();

    for entry in WalkDir::new(src_root).into_iter().filter_map(Result::ok) {
        let path = entry.path();
        if !entry.file_type().is_file() {
            continue;
        }
        if path.extension().and_then(|s| s.to_str()) != Some("rs") {
            continue;
        }

        let Ok(content) = fs::read_to_string(path) else {
            continue;
        };

        // Parse errors are ignored so one malformed file does not block all docs.
        let Ok(file) = syn::parse_file(&content) else {
            continue;
        };

        let Some(base_module) = module_path_from_file(src_root, path) else {
            continue;
        };

        let mut collector =
            FileCollector { base_module, module_stack: Vec::new(), spec_tags, out: Vec::new() };
        collector.visit_file(&file);
        out.extend(collector.out);
    }

    // Keep output order stable to make logs and doc diffs predictable.
    out.sort_by(|a, b| {
        a.module_path.cmp(&b.module_path).then_with(|| a.func_name.cmp(&b.func_name))
    });
    out
}

fn html_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            _ => out.push(ch),
        }
    }
    out
}

/// Returns true if `href` is allowed inside an injected `<a href="…">`.
///
/// Scheme A: only relative documentation paths (no `://`, no `//`, no script/data URLs).
fn is_safe_relative_href(href: &str) -> bool {
    let h = href.trim();
    if h.is_empty() {
        return false;
    }
    if h.starts_with("//") || h.contains("://") {
        return false;
    }
    let lower = h.to_ascii_lowercase();
    if lower.starts_with("javascript:")
        || lower.starts_with("data:")
        || lower.starts_with("vbscript:")
    {
        return false;
    }
    for ch in h.chars() {
        if ch.is_control() || ch.is_whitespace() {
            return false;
        }
        if matches!(ch, '"' | '\'' | '<' | '>' | '\\' | '`' | '{' | '}') {
            return false;
        }
    }
    true
}

fn is_safe_url_fragment(fragment: &str) -> bool {
    !fragment.is_empty()
        && fragment
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-')
}

/// URL path from `from_dir` to `to_file` using `/` (rustdoc layout).
fn href_path_relative(from_dir: &Path, to_file: &Path) -> Option<String> {
    let from_c: Vec<Component<'_>> = from_dir.components().collect();
    let to_c: Vec<Component<'_>> = to_file.components().collect();
    let mut i = 0usize;
    let n = from_c.len().min(to_c.len());
    while i < n && from_c[i] == to_c[i] {
        i += 1;
    }
    let mut out = String::new();
    for _ in i..from_c.len() {
        out.push_str("../");
    }
    while i < to_c.len() {
        match to_c[i] {
            Component::Normal(name) => {
                out.push_str(&name.to_string_lossy());
                if i + 1 < to_c.len() {
                    out.push('/');
                }
                i += 1;
            }
            _ => return None,
        }
    }
    (!out.is_empty()).then_some(out)
}

/// Per-function injection context: resolves `@mod:…#…` against the current `fn.*.html` location.
struct LinkContext<'a> {
    doc_root: &'a Path,
    crate_name: &'a str,
    module_path: &'a [String],
    fn_name: &'a str,
}

impl LinkContext<'_> {
    /// `[label](@mod:ptr#safety)` or `[label](@mod:mem::maybe_uninit#safety)` → relative `href`.
    fn resolve_markdown_href(&self, href: &str) -> Option<String> {
        let href = href.trim();
        let spec = href.strip_prefix('@')?;
        let rest = spec.strip_prefix("mod:")?;
        let (mod_path, fragment) = match rest.split_once('#') {
            Some((m, f)) => (m.trim(), f.trim()),
            None => (rest.trim(), ""),
        };
        if !fragment.is_empty() && !is_safe_url_fragment(fragment) {
            return None;
        }
        let segments: Vec<&str> =
            mod_path.split("::").map(str::trim).filter(|s| !s.is_empty()).collect();
        if segments.is_empty() {
            return None;
        }
        for seg in &segments {
            if !seg.chars().all(|c| c.is_ascii_alphanumeric() || c == '_') {
                return None;
            }
        }
        let mut target = self.doc_root.to_path_buf();
        target.push(self.crate_name);
        for seg in segments {
            target.push(seg);
        }
        target.push("index.html");
        let current_fn = expected_fn_html_path(self.doc_root, self.crate_name, self.module_path, self.fn_name);
        let from_dir = current_fn.parent()?;
        let mut rel = href_path_relative(from_dir, &target)?;
        if !fragment.is_empty() {
            rel.push('#');
            rel.push_str(fragment);
        }
        is_safe_relative_href(&rel).then_some(rel)
    }
}

/// Parses `[text](url)` in a segment that does not contain backticks (code spans are split out
/// before this runs). Invalid or unsafe links emit a literal `[` and scanning continues.
fn process_plain_with_links(s: &str, ctx: &LinkContext<'_>) -> String {
    let mut out = String::new();
    let mut rest = s;
    while let Some(open) = rest.find('[') {
        out.push_str(&html_escape(&rest[..open]));
        rest = &rest[open..];
        let Some(close_rel) = rest[1..].find(']') else {
            out.push_str(&html_escape(&rest[..1]));
            rest = &rest[1..];
            continue;
        };
        let close = 1 + close_rel;
        let link_text = &rest[1..close];
        let after = &rest[close + 1..];
        let Some(after_paren) = after.strip_prefix('(') else {
            out.push_str(&html_escape(&rest[..1]));
            rest = &rest[1..];
            continue;
        };
        let Some(close_paren_rel) = after_paren.find(')') else {
            out.push_str(&html_escape(&rest[..1]));
            rest = &rest[1..];
            continue;
        };
        let href_raw = after_paren[..close_paren_rel].trim();
        let chosen = ctx
            .resolve_markdown_href(href_raw)
            .or_else(|| is_safe_relative_href(href_raw).then(|| href_raw.to_string()));
        if let Some(ref href) = chosen {
            out.push_str("<a href=\"");
            out.push_str(&html_escape(href));
            out.push_str("\">");
            out.push_str(&html_escape(link_text));
            out.push_str("</a>");
            rest = &after_paren[close_paren_rel + 1..];
        } else {
            out.push_str(&html_escape(&rest[..1]));
            rest = &rest[1..];
        }
    }
    out.push_str(&html_escape(rest));
    out
}

/// Applies `` `code` `` → `<code>…</code>` and, outside code spans, `[text](url)` → `<a>…</a>`.
fn format_desc_to_html(input: &str, ctx: &LinkContext<'_>) -> String {
    let mut out = String::new();
    let mut s = input;
    while !s.is_empty() {
        match s.find('`') {
            Some(i) => {
                out.push_str(&process_plain_with_links(&s[..i], ctx));
                s = &s[i + 1..];
                match s.find('`') {
                    Some(j) => {
                        out.push_str("<code>");
                        out.push_str(&html_escape(&s[..j]));
                        out.push_str("</code>");
                        s = &s[j + 1..];
                    }
                    None => {
                        out.push_str("<code>");
                        out.push_str(&html_escape(s));
                        out.push_str("</code>");
                        s = "";
                    }
                }
            }
            None => {
                out.push_str(&process_plain_with_links(s, ctx));
                s = "";
            }
        }
    }
    out
}

/// One `<li><p>…</p></li>` per entry.
fn render_safety_list_html(lines: &[String], ctx: &LinkContext<'_>) -> String {
    let mut html = String::new();
    html.push_str("<ul data-safety-tool=\"true\">\n");
    for line in lines {
        for part in line.split('\n') {
            let t = part.trim();
            if t.is_empty() {
                continue;
            }
            html.push_str("<li>\n<p>");
            html.push_str(&format_desc_to_html(t, ctx));
            html.push_str("</p>\n</li>\n");
        }
    }
    html.push_str("</ul>\n");
    html
}

/// Rustdoc turns `# Safety` into `<h2 id="safety">…</h2>` (or `h3` for `## Safety`, etc.).
/// Conflicting ids become `safety-1`, `safety-2`, …
fn find_pos_after_markdown_safety_heading(html: &str) -> Option<usize> {
    const IDS: &[&str] = &["safety", "safety-1", "safety-2", "safety-3", "safety-4", "safety-5"];
    for (tag, close) in [("h2", "</h2>"), ("h3", "</h3>"), ("h4", "</h4>"), ("h5", "</h5>")] {
        for id in IDS {
            let open = format!(r#"<{tag} id="{id}""#);
            if let Some(start) = html.find(&open) {
                if let Some(rel) = html[start..].find(close) {
                    return Some(start + rel + close.len());
                }
            }
        }
    }
    None
}

fn inject_into_html_file(path: &Path, note_html: &str) -> std::io::Result<bool> {
    const START: &str = "<!-- safety-tool:start -->";
    const END: &str = "<!-- safety-tool:end -->";

    let original = fs::read_to_string(path)?;
    // Marker-wrapped block allows idempotent updates on repeated runs.
    let block = format!("{START}{note_html}{END}");

    // Replace existing marker block to keep injection idempotent.
    if let Some(start_pos) = original.find(START) {
        if let Some(end_rel) = original[start_pos..].find(END) {
            let end_pos = start_pos + end_rel + END.len();
            let mut updated = String::with_capacity(original.len() + block.len());
            updated.push_str(&original[..start_pos]);
            updated.push_str(&block);
            updated.push_str(&original[end_pos..]);
            if updated != original {
                fs::write(path, updated)?;
                return Ok(true);
            }
            return Ok(false);
        }
    }

    // First-time injection: after `# Safety` heading if present, else start of main docblock.
    let insert_at = if let Some(pos) = find_pos_after_markdown_safety_heading(&original) {
        pos
    } else {
        let Some(docblock_pos) = original.find("<div class=\"docblock\"") else {
            return Ok(false);
        };
        let Some(tag_end_rel) = original[docblock_pos..].find('>') else {
            return Ok(false);
        };
        docblock_pos + tag_end_rel + 1
    };
    let mut out = String::with_capacity(original.len() + block.len());
    out.push_str(&original[..insert_at]);
    out.push_str(&block);
    out.push_str(&original[insert_at..]);
    fs::write(path, out)?;
    Ok(true)
}

fn expected_fn_html_path(
    doc_root: &Path,
    crate_name: &str,
    module_path: &[String],
    fn_name: &str,
) -> PathBuf {
    // rustdoc function pages follow `.../fn.<name>.html`.
    let mut p = doc_root.to_path_buf();
    p.push(crate_name);
    for comp in module_path {
        p.push(comp);
    }
    p.push(format!("fn.{fn_name}.html"));
    p
}

fn inject_docs(
    doc_root: &Path,
    crate_name: &str,
    annotations: &[Annotation],
) -> std::io::Result<usize> {
    let mut changed = 0;

    for ann in annotations {
        let ctx = LinkContext {
            doc_root,
            crate_name,
            module_path: &ann.module_path,
            fn_name: &ann.func_name,
        };
        let rendered = render_safety_list_html(&ann.rendered_lines, &ctx);
        let expected =
            expected_fn_html_path(doc_root, crate_name, &ann.module_path, &ann.func_name);
        // Inject only when the expected function page exists.
        if expected.exists() {
            if inject_into_html_file(&expected, &rendered)? {
                changed += 1;
            }
        }
    }

    Ok(changed)
}

fn main() {
    let args = env::args().skip(1).collect::<Vec<_>>();

    // Paths can be overridden by bootstrap, but defaults make local testing easy.
    let src_root = parse_arg_value(&args, "--src-root")
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("library/core/src"));
    let doc_root = parse_arg_value(&args, "--doc-root")
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("build/safety-tool-doc"));
    let spec_path = parse_arg_value(&args, "--safety-spec")
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("src/tools/safety-tool/assets/sp-core.toml"));
    let documenting_crate =
        parse_arg_value(&args, "--documenting-crate").unwrap_or_else(|| "core".to_string());

    let spec = match load_safety_spec(&spec_path, &documenting_crate) {
        Ok(Some(s)) => s,
        Ok(None) => {
            eprintln!(
                "safety-tool: safety spec `package.name` does not match `--documenting-crate` ({documenting_crate}); nothing to do"
            );
            return;
        }
        Err(e) => {
            eprintln!("safety-tool: {e}");
            std::process::exit(1);
        }
    };

    let anns = collect_annotations(&src_root, &spec.tags);
    match inject_docs(&doc_root, &spec.package_name, &anns) {
        Ok(changed) => {
            eprintln!(
                "safety-tool: parsed {} annotations, injected {} html pages for crate {} using {}",
                anns.len(),
                changed,
                spec.package_name,
                spec_path.display()
            );
        }
        Err(err) => {
            eprintln!("safety-tool: failed to inject docs: {err}");
            std::process::exit(1);
        }
    }
}
